forcedotcom/datacloud-jdbc

- src/main/java/com/salesforce/datacloud/jdbc/core/DataCloudDatabaseMetadata.java
- src/main/java/com/salesforce/datacloud/jdbc/core/QueryMetadataUtil.java
- src/main/resources/sql/get_schemas_query.sql
- src/test/java/com/salesforce/datacloud/jdbc/core/QueryMetadataUtilTest.java
These changes exclude the dataspace from the lakehouse identifier when it is null as well as excluding system schemas when making the get_schemas_query.
> Metadata fixes for system schema and lakehouse identifier

- src/main/java/com/salesforce/datacloud/jdbc/core/accessor/impl/TimeStampVectorAccessor.java
- src/test/java/com/salesforce/datacloud/jdbc/core/accessor/impl/TimeStampVectorAccessorTest.java
This commit fixes the handling of UTC to local time zone conversion, which was causing incorrect date-time display in the UI.
> fix: Incorrect date-time reporting in the UI due to time zone handling

- README.md
- src/main/java/com/salesforce/datacloud/jdbc/core/ConnectionQuerySettings.java
- src/main/java/com/salesforce/datacloud/jdbc/core/HyperGrpcClientExecutor.java
- src/test/java/com/salesforce/datacloud/jdbc/core/ConnectionQuerySettingsTest.java
- src/test/java/com/salesforce/datacloud/jdbc/core/HyperConnectionSettingsTest.java
- src/test/java/com/salesforce/datacloud/jdbc/hyper/HyperServerProcess.java
- src/test/java/com/salesforce/datacloud/jdbc/hyper/HyperTestBase.java
- src/test/resources/hyper.yaml
- src/test/resources/simplelogger.properties
Server Settings are easy to be confused with global system-wide settings while users only have the mean to rename connection settings. In V3 Connect API the concept of query level settings is called "querySettings", thus we propose the same name in JDBC. We still accept the old name for transition purposes but will log a warning message.
Drive-By:
- Factor our the test Hyper Server Process management into separate class for clarity
- Improve shutdown speed by using waitFor instead of fixed 3s sleep
- Be strict on config settings as previously we had a silently a setting that hyper wouldn't recognize
- Use auto port picking for the server process to avoid accidental colissions
- Be consciously less robust on server process management during test to make any failures and problems very …
> Rename pattern from `serverSetting.` to `querySetting` for consistency

- src/main/java/com/salesforce/datacloud/jdbc/core/HyperGrpcClientExecutor.java
- src/main/java/com/salesforce/datacloud/jdbc/core/StreamingResultSet.java
- src/main/java/com/salesforce/datacloud/jdbc/core/listener/AdaptiveQueryStatusListener.java
- src/main/java/com/salesforce/datacloud/jdbc/core/listener/AsyncQueryStatusListener.java
- src/main/java/com/salesforce/datacloud/jdbc/core/listener/SyncQueryStatusListener.java
- src/main/java/com/salesforce/datacloud/jdbc/exception/QueryExceptionHandler.java
- src/test/java/com/salesforce/datacloud/jdbc/core/JDBCLimitsTest.java
With this change we are checking limits around:
- headers
- request size
- parameter sizes
The driver already passed all limits but the tests uncoverd a significant inefficiency around exception creation. With multi megabyte queries this was causing multi second hangs. Thus we now truncate the query in the exception message.
If the query is truncated it'll have a `<truncated>` suffix
> fix: Truncate query in exceptions and add test coverage for protocol limits

- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/DataCloudConnection.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/interceptor/SingleHeaderMutatingClientInterceptor.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/AsyncStreamingResultSetTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/partial/ChunkBasedTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/examples/SubmitQueryAndConsumeResultsTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/hyper/HyperServerProcess.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/hyper/HyperTestBase.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/interceptor/EmittedHeaderTest.java
- pom.xml
The intent of this change is to analyze how to use the JDBC driver in the least invasive way (compared to manual gRPC calling). To reach that minimum the `DataCloudConnection.fromChannel` method was adjusted to only add the must have interceptors, which - without usage of the corresponding connection parameters - are complete no ops.
To demonstrate this flow a new `examples` test package was create that demonstrates the approach and serves as documentation. To write that test case (and minimize the use of helpers which would hide complexity) the test hyper instance variable with its getPort method was exposed as public.
Drive-By:t
- The hyper test instance was made non-static to avoid problems in parallel test execution.
- A sample implementation of using the row based API to serve row …
> Adjust `fromChannel` method to minimize injected headers and add examples

- .github/workflows/reusable-build-publish.yml
- .gitignore
- buildSrc/src/main/kotlin/hyper-conventions.gradle.kts
- buildSrc/src/main/kotlin/publishing-conventions.gradle.kts
- buildSrc/src/main/kotlin/version-conventions.gradle.kts
- jdbc-core/build.gradle.kts
- jdbc-grpc/build.gradle.kts
- settings.gradle.kts
- verification/build.gradle.kts
Separates proto files from jdbc-grpc classifier artifact into a dedicated jdbc-proto. This improves visibility and accessibility of the proto files for consumers who need them without requiring the full grpc implementation.
> build: Restore separate jdbc-proto artifact for better visibility

- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/listener/AdaptiveQueryStatusListener.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/partial/DataCloudQueryPollingMockTests.java
Enhancements to query result handling:
* [`jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/listener/AdaptiveQueryStatusListener.java`](diffhunk://#diff-c22f047bc3e8cd467e08d7343f2ca7025eab4aa351895dae3fd4d456615b0620R116-R127): Added the `allResultsInHead` method to check if all results are produced and the chunk count is less than 2, and used this method in the `tail` method to return an empty stream if all results are in the head.
New test case:
* [`jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/partial/DataCloudQueryPollingMockTests.java`](diffhunk://#diff-f6307e3bd1b0c180e5088a11d03bafc751addf629f6ad8059951763bd7a63348R92-R106): Added the `noFinalGetQueryInfoOnSmallData` test to verify that `getQueryInfo` is not called when dealing with small data sets.
> fix:  prevent subsequent getQueryInfo on small query

- .gitignore
- buildSrc/src/main/kotlin/java-conventions.gradle.kts
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/DataCloudConnection.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/DataCloudResultSet.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/HyperGrpcClientExecutor.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/StreamingResultSet.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/listener/AdaptiveQueryStatusListener.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/listener/AsyncQueryStatusListener.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/listener/QueryStatusListener.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/partial/DataCloudQueryPolling.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/partial/RowBased.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/listener/AsyncQueryStatusListenerTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/listener/QueryStatusListenerAssert.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/partial/ChunkBasedTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/partial/RowBasedTest.java
- jdbc-core/src/test/resources/simplelogger.properties
- jdbc-util/build.gradle.kts
- jdbc-util/src/main/java/com/salesforce/datacloud/jdbc/logging/ElapsedLogger.java
- jdbc/src/main/java/com/salesforce/datacloud/jdbc/DataCloudJDBCDriver.java
We want to see logging for time to establish connection as well as most gRPC calls. This is an MVP change to get that done without a much larger refactor that I found myself making by using a decorator pattern.
> Add simple logging for key areas

- .gitignore
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/accessor/QueryJDBCAccessorFactory.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/accessor/impl/FloatVectorAccessor.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/Float4VectorTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/accessor/impl/FloatVectorAccessorTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/util/RootAllocatorTestExtension.java
This change adds support for the Float4Vector data type in the JDBC driver, allowing proper handling of 32-bit floating point numbers.
> feature: Add Float4Vector support - Add FloatVectorAccessor, tests, and wire up in factory

- gradle.properties
- gradle/libs.versions.toml
- jdbc-http/build.gradle.kts
- jdbc-http/src/main/java/com/salesforce/datacloud/jdbc/http/ClientBuilder.java
- jdbc-http/src/main/java/com/salesforce/datacloud/jdbc/http/HttpClientLogger.java
- jdbc-util/src/main/java/com/salesforce/datacloud/jdbc/util/PropertiesExtensions.java
- jdbc-util/src/test/java/com/salesforce/datacloud/jdbc/util/PropertiesExtensionsTest.java
- jdbc/src/main/java/com/salesforce/datacloud/jdbc/DataCloudJDBCDriver.java
This pull request introduces several updates, primarily focusing on enhancing logging capabilities.
* Added HTTP logging support in `jdbc-http` by introducing a new `HttpClientLogger` class and integrating `HttpLoggingInterceptor` into the `OkHttpClient` builder. Logging levels can now be configured via a new property, `okhttp.logging.level`
* Added utility methods `getEnumOrDefault` and `toEnumOrDefault` to `PropertiesExtensions` for safer and more flexible enum handling
* Updated the `revision` property in `gradle.properties` to `0.27.0-SNAPSHOT`
* Integrated a new `TracingHeadersInterceptor` into the gRPC `ManagedChannelBuilder` in the `jdbc` module to enhance tracing capabilities
> feat: add http logging and grpc tracing from oauth driver

- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/interceptor/TracingHeadersInterceptor.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/interceptor/EmittedHeaderTest.java
- jdbc-http/src/main/java/com/salesforce/datacloud/jdbc/auth/DataCloudTokenProcessor.java
- jdbc-http/src/main/java/com/salesforce/datacloud/jdbc/soql/DataspaceClient.java
- jdbc-util/src/main/java/com/salesforce/datacloud/jdbc/tracing/EncodingUtils.java
- jdbc-util/src/main/java/com/salesforce/datacloud/jdbc/tracing/TemporaryBuffers.java
- jdbc-util/src/main/java/com/salesforce/datacloud/jdbc/tracing/Tracer.java
- jdbc-util/src/test/java/com/salesforce/datacloud/jdbc/tracing/EncodingUtilsTest.java
- jdbc-util/src/test/java/com/salesforce/datacloud/jdbc/tracing/TemporaryBuffersTest.java
- jdbc-util/src/test/java/com/salesforce/datacloud/jdbc/tracing/TracerTest.java
This pull request includes changes to update dependencies, improve logging, and reorganize the tracing utilities. 
* Added `flattenJars` task to easily test with dbeaver without needing to wait for publication to maven central
* Updated the `revision` property in `gradle.properties` from `0.26.1` to `0.26.2`.
* Added a new dependency for `protobuf-java` in `gradle/libs.versions.toml` and included it in the `grpc-impl` bundle.
* Added logging for the `lakehouse` response in the `getLakehouse` method of `DataCloudTokenProcessor`.
* Introduced `logTimedValue` for measuring execution time in the `DataspaceClient` class and added trace and span IDs to HTTP headers for better tracing.
* Moved tracing-related classes (`EncodingUtils`, `TemporaryBuffers`, `Tracer`, and their tests) from the …
> fix: add missing protobuf-java library and add flattenJars task

- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/DataCloudConnection.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/util/DirectDataCloudConnection.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/HyperGrpcTestBase.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/examples/ChunkBasedPaginationTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/examples/RowBasedPaginationTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/examples/SubmitQueryAndConsumeResultsTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/hyper/HyperTestBase.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/interceptor/EmittedHeaderTest.java
- jdbc/src/main/java/com/salesforce/datacloud/jdbc/DataCloudJDBCDriver.java
We realized that allowing someone to opt-out of `closeChannelWithConnection` when constructing a `DataCloudConnection` with a `ManagedChannelBuilder` would cause the driver to leak that connection.
This change removes those overloads and just passes `true` to the one build method that accepts a `DataCloudJdbcManagedChannel` and `closeChannelWithConnection`, therefore someone who has a handle to the channel and knows they opted out of automatic cleanup can clean up their channel later.
> fix: using channel builder in DataCloudConnection should always cleanup

- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/DataCloudResultSet.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/StreamingResultSet.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/StreamingResultSetTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/listener/AdaptiveQueryStatusListenerTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/listener/AsyncQueryStatusListenerTest.java
This commit de-obfuscates the code inside the `StreamingResultSet`.
The `listener` was always set to an `AlreadyReadyNoopListener` which is essentially nothing else than a wrapper around the query-id. All its other variables (e.g., `ready`) were hardcoded. Maybe this abstraction served some actual purpose at some earlier time, but by now it was only obfuscating the code.
This commit removes that code obfuscation.
After deobfuscation, it became obvious that `DataCloudResultSet.isReady` was essentially hard-coded to true. As such, I am also removing that function in this commit.
> Remove `listener` from `StreamingResultSet`

- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/MetadataResultSet.java
This should fix an issue where tools that make use of DatabaseMetaData expect a more complete result set. Unfortunately, the Avatica ResultSet is difficult to make forward only through its constructor. So instead, we extend that ResultSet and override the forward only related methods.
> fix: force MetadataResultSet to be forward only

- README.md
- gradle.properties
- gradle/libs.versions.toml
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/DataCloudConnection.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/HyperGrpcClientExecutor.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/listener/AdaptiveQueryStatusListener.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/listener/AsyncQueryStatusListener.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/partial/DataCloudQueryPolling.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/DataCloudStatementFunctionalTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/partial/ChunkBasedTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/partial/RowBasedTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/examples/ResultScanTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/hyper/HyperServerProcess.java
- jdbc-core/src/test/resources/hyper.yaml
This will allow callers to wait for a query to satisfy their own criteria while also benefiting from the existing retry logic that is already in place for waiting for chunks or rows.
> feat: expose polling for a query status by arbitrary predicate

- jdbc-core/build.gradle.kts
I noticed jackson databind wasn't being used in jdbc-core anymore so I pulled that out of the build file
> remove unused 3pl for jdbc-core

- .github/workflows/reusable-build-publish.yml
- .gitignore
- buildSrc/src/main/kotlin/hyper-conventions.gradle.kts
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/partial/DataCloudQueryPollingMockTests.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/exception/QueryExceptionHandlerTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/hyper/HyperServerProcess.java
Since I don't have a windows machine to run this on to fix #56 I figured it might be a good idea to add a windows target to our build matrix. I also updated the hyper gradle tasks with inputs/outputs to help gradle decide how to cache.
This mostly adds a Windows build step, so build and test now run in parallel on both Linux and Windows. Because of differences in shells between Linux and Windows, I decided to use a GitHub Action to display the file tree on failure, rather than writing logic to run ls correctly on each platform. Otherwise, this file is essentially unchanged.
This makes some minor changes to include support for x86_64 macOS, and properly wires through the subtle differences in the Windows zip compared to the Linux zip. For example, hyperd.exe is in bin instead of lib like …
> build: add windows to build matrix and caching to gradle hyper tasks

- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/listener/AdaptiveQueryStatusListener.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/listener/AsyncQueryStatusListener.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/listener/QueryStatusListener.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/listener/AdaptiveQueryStatusListenerTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/listener/AsyncQueryStatusListenerTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/listener/QueryStatusListenerAssert.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/listener/QueryStatusListenerTest.java
Both functions were used exclusively in test cases and served no actual
purpose. Also the two test cases served no purpose:
* `itCanGetStatus` and `itKeepsTrackOfQueryAndQueryId` only checked that
both functions were implemented correctly.
* `itWillWaitUntilResultsProducedOrFinishedToProduceStatus` did not
actually test any waiting, despite what the test case name claimed.
Instead, the test expectations were setup, such that the `hasStatus`
was fulfilled already on the first call, making this another call
which essentially only checked that `getStatus` actually gets the
status
> Remove `QueryStatusListener.get{Status,Query}`

- gradle.properties
- jdbc-proto/src/main/proto/error_details.proto
- jdbc-proto/src/main/proto/hyper_service.proto
In particular, this upgrade includes support for two new parameters:
* `QueryInfoParam.schema_output_format` allows to fetch the schema using a query-id, even if the query produced zero rows, and hence also zero chunks. This will be required for the Spark driver to retrieve the schema of a query result given a query-result-id.
* `QueryParam.query_row_limit` allows to fetch the result of a SQL query without actually running the query. This will be required for submitting a Hyper-SQL query from the Spark-SQL connector.
Furthermore, with this update we are also including all comments in the `.proto` files. This will make it easier to improve the JDBC driver in the future without always having to keep the internal version of this file open in a separate tab.
> chore: Upgrade Hyper API to 0.0.22502

- README.md
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/DataCloudConnection.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/DataCloudPreparedStatement.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/DataCloudStatement.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/HyperGrpcClientExecutor.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/StatementProperties.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/listener/AdaptiveQueryStatusListener.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/listener/AsyncQueryStatusListener.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/partial/DataCloudQueryPolling.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/interceptor/NetworkTimeoutInterceptor.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/util/Constants.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/util/Deadline.java
- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/util/QueryTimeout.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/DataCloudConnectionFunctionalTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/HyperGrpcClientTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/PropertiesTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/QueryTimeoutTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/listener/AdaptiveQueryStatusListenerTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/listener/AsyncQueryStatusListenerTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/listener/QueryStatusListenerTest.java
This change adjusts the query timeout handling from being locally  + gRPC deadline enforced to now primarily being enforced on Hyper server side.
- This allows to return the server side error to the caller. Previously it would either raise an internal error by the JDBC driver or obscure gRPC timeout errors depending on which layer detected the problem first.
- It now also guarantees that async queries don't exceed their timeout even if the client crashes / or the user flow forgets to explicitly invoke `cancel`.
To ensure robustness of the query timeout handling in face of network problems or even server side bugs this change doesn't only rely on the server side timeouts.
As a safety net there is also local enforcement (which happens with a configurable delay to allow the server to …
> feat: Improved query timeout handling

- jdbc-core/src/main/java/com/salesforce/datacloud/jdbc/core/fsm/AdaptiveQueryResultIterator.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/HyperGrpcTestBase.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/fsm/AdaptiveQueryResultIteratorFunctionalTest.java
- jdbc-core/src/test/java/com/salesforce/datacloud/jdbc/core/fsm/AdaptiveQueryResultIteratorTest.java
- jdbc-core/src/testFixtures/java/com/salesforce/datacloud/jdbc/hyper/HyperServerManager.java
This pull request improves the resilience and correctness of the `AdaptiveQueryResultIterator` by handling gRPC `CANCELLED` exceptions during query streaming, ensuring retry logic is properly implemented and tested -- the "finite state machine" will never give up due to a `CANCELLED` status code. Also, replaces #90
> feat: add getQueryInfo retry mechanism for usage in FSMs

- .github/workflows/reusable-build-publish.yml
GitHub Actions doesn't really let you inspect its caches, but I suspect since cache misses are uploaded at the end of a job that we're storing log files unnecessarily.
> ci: be more specific with hyper caching in ci

- .github/workflows/reusable-build-publish.yml
- gradle.properties
JReleaser release is failing with a **409 Conflict error** when trying to publish snapshot artifacts to GitHub Packages.
> fix: update version to 0.35.0 and resolves 409 conflict error in snapshot builds

- .github/workflows/reusable-build-publish.yml
- JReleaser 1.20.0 introduced stricter GPG public key validation
- This caused publishing failures with 'Did not find public key for signing' error
- Pinning to 1.19.0 restores working behavior from previous releases
- Resolves verification, bundle, and publishing issues in release workflow
Fixes publishing failures experienced in version 0.35.0 release.
> fix: pin JReleaser to version 1.19.0 to resolve GPG signing issues

- buildSrc/src/main/kotlin/shading.gradle.kts
- Fix IllegalArgumentException: Address types of NameResolver 'unix' not supported
- Root cause: Shadow plugin's duplicatesStrategy=EXCLUDE prevented merging of service files from multiple JARs (grpc-core and grpc-netty)
- Solution: Set duplicatesStrategy=INCLUDE globally, EXCLUDE for non-service files
- Ensures both DnsNameResolverProvider and UdsNameResolverProvider are included
- Resolves URI scheme resolution from unix:// back to proper dns://
Fixes version 0.35.0 regression where shaded JAR was missing critical gRPC providers
> fix: resolve gRPC NameResolver service file merging in shaded JAR
